---
- hosts: all_ubuntu
  become: true
  tasks:
    - name: Updating and upgrading packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Installing aptitude
      package:
        name: aptitude
        state: latest
   
    - name: installing ptop
      package:
        name: ptop
        state: latest

    - name: installing ntop
      package:
        name: ntop
        state: latest

    - name: installing sysstat
      package:
        name: sysstat
        state: latest

    - name: installing awstats
      package:
        name: awstats
        state: latest
